### PR TITLE
Optionally create repo; allow creation simply from file specification

### PR DESCRIPTION
**Pull request by ajcrites**

### CODE REVIEW

**Comment by mbostock** [comment]
So, you don’t want to create the git repo? Why not? That’s kind of the design of this tool.

It would be nice to make the initial post to GitHub API using the actual file contents, though. That would fix a caching issue I see occasionally. I created a separate issue #21 to track that request.

**Comment by ajcrites** [comment]
I left creation of the repo as the default behavior.  It has to be disabled explicitly.

Most of the time when using this tool I wouldn't want to create a repo, though.  I have a lot of reasons, so I'll list some:

* Creating the repo takes longer, generates more output
* Change allows you to create gists from file paths
* Change allows you to create gists for files in directories for which you lack write access
* You don't have to worry about what happens when running `gistup` while already in a repo, particularly one that doesn't have a gist origin
* Avoids creating repos where you don't want them even -- this was the genesis for this change. I created a gist for a file in my home directory which had pretty disastrous results.

Let me know if you disagree with this change and I'll fork this project since it is really handy. Otherwise, let me know how you would like me to handle the conflict (rebase or merge?)

**Comment by mbostock** [comment]
This feels more like a fork to me because of how significantly this changes the functionality.

**Comment by ajcrites** [comment]
No problem; I'll create a separate package.

**Pull request closed without merging**
